import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#11112a",
        "on-tertiary-fixed-variant": "#653e00",
        "secondary-fixed-dim": "#d0bcff",
        "on-secondary-fixed": "#23005c",
        "surface-tint": "#c0c1ff",
        secondary: "#d0bcff",
        "primary-fixed": "#e1e0ff",
        "surface-container-highest": "#32324d",
        "on-primary-fixed": "#07006c",
        "tertiary-container": "#ca8100",
        "tertiary-fixed-dim": "#ffb95f",
        "tertiary-fixed": "#ffddb8",
        "error-container": "#93000a",
        "on-error": "#690005",
        "inverse-surface": "#e2dfff",
        "secondary-fixed": "#e9ddff",
        "on-secondary-container": "#c4abff",
        "primary-fixed-dim": "#c0c1ff",
        "on-surface": "#e2dfff",
        "surface-bright": "#373752",
        "surface-container-lowest": "#0b0b24",
        background: "#11112a",
        "on-primary": "#1000a9",
        "on-primary-container": "#0d0096",
        "on-primary-fixed-variant": "#2f2ebe",
        "primary-container": "#8083ff",
        "inverse-primary": "#494bd6",
        "on-secondary": "#3c0091",
        "surface-container-high": "#272742",
        "surface-container-low": "#191932",
        "on-background": "#e2dfff",
        primary: "#c0c1ff",
        "outline-variant": "#464554",
        "surface-container": "#1d1d37",
        "surface-variant": "#32324d",
        "on-surface-variant": "#c7c4d7",
        surface: "#11112a",
        "on-secondary-fixed-variant": "#5516be",
        "secondary-container": "#571bc1",
        tertiary: "#ffb95f",
        "on-tertiary-fixed": "#2a1700",
        outline: "#908fa0",
        "on-tertiary": "#472a00",
        "on-tertiary-container": "#3e2400",
        "on-error-container": "#ffdad6",
        error: "#ffb4ab",
        "inverse-on-surface": "#2e2e48",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xs: "8px",
        lg: "40px",
        gutter: "20px",
        "container-max": "1200px",
        base: "4px",
        xl: "64px",
        md: "24px",
        sm: "16px",
        safe: "env(safe-area-inset-bottom)",
      },
      fontFamily: {
        "headline-lg-mobile": ["Outfit", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg": ["Outfit", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-md": ["Outfit", "sans-serif"],
        "headline-sm": ["Outfit", "sans-serif"],
        "headline-xl": ["Outfit", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
      keyframes: {
        shimmer: {
          "100%": { transform: "translateX(100%)" },
        },
      },
      animation: {
        shimmer: "shimmer 2s infinite",
      },
    },
  },
  plugins: [],
};

export default config;
